### ISSUE TITLE
Project Ayachan V3 roadmap

### ISSUE THREAD

**Issue by 6QHTSK** [6QHTSK/ayachan#2]
~~写个roadmap画画饼~~

# Project Ayachan V3.0

Project Ayachan是一个帮助Bestdori谱师与谱面爱好者对自己的谱面检查、定级、测试、管理的项目，并未来计划支持更多的自制谱社区，其补充了部分Bestdori自制谱网站对于谱师所不具备的功能。当前，该项目已迭代至V2.1。即将在未来更新到V3版本。

Ayachan将在未来的V3版本从当前的宏模块重构拆分为多个模块，并采用docker image的形式进行模块的部署。

以下是各个模块的详细功能与当前更新进度，未来子模块的更新roadmap会单开一个issue。

### Bestdori-Proxy（从[ayachan-bestdoriAPI](https://github.com/6QHTSK/ayachan-bestdoriAPI)迭代而来）

该模块负责整合Bestdori和Sonolus相关信息，将官方谱面、自制谱面相关信息接口统一为一个接口。并将Bestdori返回的嵌套的json展平。

- [x] Bestdori 官方与自制谱面接口（包括帖子信息、谱面内容）
- [x] Bestdori 谱面列表（包括官谱、自制，以下省略）
- [x] Bestdori 封面反代
- [x] Bestdori 音频反代
- [x] Sonolus Bestdori服务器资源反代

### Bandori-Difficulty-Analyzer

该部分负责帮助谱师对各种Bestdori谱面进行定级。由于官方修正了谱面难度，推出了高难谱面，为了迎合官方的难度增强和社区的要求，将会在原有定级器的基础上，全面解除之前只对传统Bandori谱面定级的限制，力求对任意输入的，可发布到Bestdori的谱面均可以定级（当然还是对传统的定级准确度更高）。

**定级器只是一个工具，它帮助谱师与谱面爱好者标定难度，请不要将定级结果奉为圭臬。**

- [ ] SP键标志
- [ ] 谱面Metrics提取
- [ ] 标定难度拟合
- [ ] Metrics权重确认
- [ ] 定级准确度测试
- [ ] 蓝白定级器V16支持

### Chart-Format-Converter

谱面格式转换器，以BDv2为基础格式。

- [ ] BDv2 -> Sonolus
- [ ] BDv2 <-> ebbbv2
- [ ] 【远期】BDv2 <-> banground

### Sonolus-Server-for-Testing

测试服务器。将在原有的测试服务器上，增加以下功能。

- [ ] 单次提交表单即可上传到测试服务器。
- [ ] 可以参考Bestdori帖子的形式浏览已上传的测试谱面，并提供相应API。
- [ ] 上传谱面输出格式可指定（存储采用BDv2，Sonolus游玩返回Sonolus格式）
- [ ] 测试谱面难度标定。
- [ ] 可以修改、删除谱面。（使用token鉴权，存储于浏览器中）
- [ ] Expired时间多样化，从1小时到7天不等。
- [ ] 隐藏谱面支持，需要在搜索框中准确输入id才能找到该谱面。（包括浏览器端和Sonolus端）

### 网页重构计划

网页更新到V1.0版本，使用element-ui重构。

- [ ] 分享谱面页更新
- [ ] 定级器页面API更新
- [ ] Sonolus测试服页面API更新
- [ ] Sonolus测试服浏览器查询
- [ ] 暂时移除按谱师搜索服务器浏览器查询页面

### Bandori-Chart-Analyzer（从[Bandori-Chart-Analysiser](https://github.com/6QHTSK/Bandori-Chart-Analysiser)迭代而来）

原有的定级器的部分功能将整合到这个模块中，这个模块会模拟游玩自制谱师的谱面（以双指的形式），给出双指拆分情况，并对谱面依照给定等级给出建议。

- [ ] 多指、反手不会打断游玩，分析器会放弃部分音符。
- [ ] 增加骗手警示
- [ ] 增加密度过大警示（单指或局部）
- [ ] 保留原有定级器对传统谱面才显示的数据

### Advaced-Bestdori-Sonolus-Server（从[ayachan-sonolus](https://github.com/6QHTSK/ayachan-sonolus)迭代而来）

按谱师搜索服务器复活，可支持以下功能。

- [ ] 同步谱面列表，同步信息可查询
- [ ] 谱面基本信息标注（SP键、谱面长度标注、反手、多压、Note数、长度等）
- [ ] LONG（>2分30秒）长谱面、FULL（>3分30秒）、EXHAUST（>10分钟）标识
- [ ] 搜索模式高级化，可以对SP键谱面、创新谱面（反手/多压）、过长谱面，难度区间进行过滤
- [ ] 支持谱师搜索
- [ ] 支持全文搜索

### Custom-Bestdori-Sonolus-Server

给谱师/谱面爱好者一个独属于自己的Sonolus服务器！支持次等级，支持从Bestdori导入谱面或上传谱面到Ayachan。

### Bandori-Difficulty-Analyzer-AI

用自注意力AI模型处理Bandori谱面，并给出推测难度。
